# Generated by Django 3.2.3 on 2021-05-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_add_author', 'Can add author'), ('can_edit_author', 'Can edit author'), ('can_delete_author', 'Can delete author'), ('can_view_author', 'Can view author details'))},
        ),
    ]
